2022-09-18 14:25:00,600 WARNING client.py | PyNaCl is not installed, voice will NOT be supported
2022-09-18 14:25:00,601 DEBUG client.py | setup_hook has successfully been registered as an event
2022-09-18 14:25:00,601 DEBUG proactor_events.py | Using proactor: IocpProactor
2022-09-18 14:25:00,602 INFO client.py | logging in using static token
2022-09-18 14:25:00,602 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/@me
2022-09-18 14:25:00,905 DEBUG main.py | Request ended | https://discord.com/api/v10/users/@me
2022-09-18 14:25:00,906 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/oauth2/applications/@me
2022-09-18 14:25:01,057 DEBUG main.py | Request ended | https://discord.com/api/v10/oauth2/applications/@me
2022-09-18 14:25:01,076 DEBUG main.py | Starting request | GET | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 14:25:01,459 DEBUG main.py | Request ended | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 14:25:01,686 INFO gateway.py | Shard ID None has connected to Gateway (Session ID: b788095dd61c5a280fd9b59d642045b5).
2022-09-18 14:25:03,694 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/468631903390400527
2022-09-18 14:25:03,845 DEBUG main.py | Request ended | https://discord.com/api/v10/users/468631903390400527
2022-09-18 14:25:11,835 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/guilds/685237806360035354/members/468631903390400527
2022-09-18 14:25:12,013 DEBUG main.py | Request ended | https://discord.com/api/v10/guilds/685237806360035354/members/468631903390400527
2022-09-18 14:25:12,014 DEBUG main.py | Starting request | POST | https://discord.com/api/v10/channels/1017545677674385529/messages
2022-09-18 14:25:12,224 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1017545677674385529/messages
2022-09-18 14:25:12,224 DEBUG main.py | Starting request | PUT | https://discord.com/api/v10/channels/1017545677674385529/messages/1021049256896909372/reactions/%F0%9F%8E%89/@me
2022-09-18 14:25:12,491 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1017545677674385529/messages/1021049256896909372/reactions/%F0%9F%8E%89/@me
2022-09-18 14:25:12,788 DEBUG main.py | Starting request | DELETE | https://discord.com/api/v10/channels/1017545677674385529/messages/1021049255311450152
2022-09-18 14:25:13,008 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1017545677674385529/messages/1021049255311450152
2022-09-18 14:25:14,017 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/channels/1017545677674385529/messages/1021049256896909372
2022-09-18 14:25:14,195 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1017545677674385529/messages/1021049256896909372
2022-09-18 14:25:14,196 DEBUG main.py | Starting request | PATCH | https://discord.com/api/v10/channels/1017545677674385529/messages/1021049256896909372
2022-09-18 14:25:14,377 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1017545677674385529/messages/1021049256896909372
2022-09-18 14:25:14,378 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/channels/1017545677674385529/messages/1021049256896909372/reactions/%F0%9F%8E%89?limit=1
2022-09-18 14:25:14,563 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1017545677674385529/messages/1021049256896909372/reactions/%F0%9F%8E%89?limit=1
2022-09-18 14:25:14,637 ERROR base_events.py | Task exception was never retrieved
future: <Task finished name='Task-19' coro=<Giveaways.end_giveaway() done, defined at C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\giveaways.py:352> exception=TypeError("unsupported operand type(s) for +: 'NoneType' and 'str'")>
Traceback (most recent call last):
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\giveaways.py", line 437, in end_giveaway
    return await channel.send(embed=template.no_winner(jump_url))
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\discord_templates.py", line 168, in no_winner
    description=message + f'\n[Jump to giveaway]({jump_url})'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2022-09-18 14:25:39,870 WARNING client.py | PyNaCl is not installed, voice will NOT be supported
2022-09-18 14:25:39,872 DEBUG client.py | setup_hook has successfully been registered as an event
2022-09-18 14:25:39,872 DEBUG proactor_events.py | Using proactor: IocpProactor
2022-09-18 14:25:39,874 INFO client.py | logging in using static token
2022-09-18 14:25:39,875 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/@me
2022-09-18 14:25:40,176 DEBUG main.py | Request ended | https://discord.com/api/v10/users/@me
2022-09-18 14:25:40,177 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/oauth2/applications/@me
2022-09-18 14:25:40,386 DEBUG main.py | Request ended | https://discord.com/api/v10/oauth2/applications/@me
2022-09-18 14:25:40,418 DEBUG main.py | Starting request | GET | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 14:25:40,767 DEBUG main.py | Request ended | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 14:25:41,022 INFO gateway.py | Shard ID None has connected to Gateway (Session ID: e1497d26ef5bca8414bfa40747364ae0).
2022-09-18 14:25:43,041 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/468631903390400527
2022-09-18 14:25:43,194 DEBUG main.py | Request ended | https://discord.com/api/v10/users/468631903390400527
2022-09-18 14:26:03,597 WARNING client.py | PyNaCl is not installed, voice will NOT be supported
2022-09-18 14:26:03,599 DEBUG client.py | setup_hook has successfully been registered as an event
2022-09-18 14:26:03,600 DEBUG proactor_events.py | Using proactor: IocpProactor
2022-09-18 14:26:03,602 INFO client.py | logging in using static token
2022-09-18 14:26:03,603 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/@me
2022-09-18 14:26:03,923 DEBUG main.py | Request ended | https://discord.com/api/v10/users/@me
2022-09-18 14:26:03,924 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/oauth2/applications/@me
2022-09-18 14:26:04,183 DEBUG main.py | Request ended | https://discord.com/api/v10/oauth2/applications/@me
2022-09-18 14:26:04,199 DEBUG main.py | Starting request | GET | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 14:26:04,540 DEBUG main.py | Request ended | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 14:26:04,758 INFO gateway.py | Shard ID None has connected to Gateway (Session ID: 6a906cf7eeb153c0728721fc7936a8cc).
2022-09-18 14:26:06,764 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/468631903390400527
2022-09-18 14:26:06,914 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/guilds/685237806360035354/members/468631903390400527
2022-09-18 14:26:06,923 DEBUG main.py | Request ended | https://discord.com/api/v10/users/468631903390400527
2022-09-18 14:26:07,129 DEBUG main.py | Request ended | https://discord.com/api/v10/guilds/685237806360035354/members/468631903390400527
2022-09-18 14:26:07,130 DEBUG main.py | Starting request | POST | https://discord.com/api/v10/channels/1017545677674385529/messages
2022-09-18 14:26:07,235 DEBUG main.py | Starting request | POST | https://discord.com/api/v10/users/@me/channels
2022-09-18 14:26:07,236 ERROR client.py | Ignoring exception in on_command_error
Traceback (most recent call last):
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\main.py", line 127, in on_command_error
    message = await bot.owner.send(embed=template.error(f'```{tb_str}```', ctx.message.jump_url))
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\discord\abc.py", line 1497, in send
    channel = await self._get_channel()
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\discord\user.py", line 454, in _get_channel
    ch = await self.create_dm()
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\discord\user.py", line 496, in create_dm
    data: DMChannelPayload = await state.http.start_private_message(self.id)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\discord\http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\client.py", line 559, in _request
    await resp.start(conn)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\client_reqrep.py", line 583, in write_bytes
    await self.body.write(writer)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\payload.py", line 247, in write
    await writer.write(self._value)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\http_writer.py", line 89, in write
    await self._on_chunk_sent(chunk)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\client_reqrep.py", line 703, in _on_chunk_request_sent
    await trace.send_request_chunk_sent(method, url, chunk)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\tracing.py", line 366, in send_request_chunk_sent
    return await self._trace_config.on_request_chunk_sent.send(
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiosignal\__init__.py", line 36, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\main.py", line 37, in on_request_chunk_sent
    json.dumps(param.chunk, indent=4, ensure_ascii=False)
  File "C:\Users\Franky\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\Franky\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Users\Franky\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\Franky\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
2022-09-18 14:28:28,372 WARNING client.py | PyNaCl is not installed, voice will NOT be supported
2022-09-18 14:28:28,373 DEBUG client.py | setup_hook has successfully been registered as an event
2022-09-18 14:28:28,373 DEBUG proactor_events.py | Using proactor: IocpProactor
2022-09-18 14:28:28,374 INFO client.py | logging in using static token
2022-09-18 14:28:28,375 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/@me
2022-09-18 14:28:28,706 DEBUG main.py | Request ended | https://discord.com/api/v10/users/@me
2022-09-18 14:28:28,706 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/oauth2/applications/@me
2022-09-18 14:28:28,882 DEBUG main.py | Request ended | https://discord.com/api/v10/oauth2/applications/@me
2022-09-18 14:28:28,894 DEBUG main.py | Starting request | GET | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 14:28:29,260 DEBUG main.py | Request ended | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 14:28:29,471 INFO gateway.py | Shard ID None has connected to Gateway (Session ID: 06c94c38f8e9e21ca4b388d53fa795e6).
2022-09-18 14:28:31,482 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/468631903390400527
2022-09-18 14:28:31,695 DEBUG main.py | Request ended | https://discord.com/api/v10/users/468631903390400527
2022-09-18 14:28:32,408 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/guilds/685237806360035354/members/468631903390400527
2022-09-18 14:28:32,604 DEBUG main.py | Request ended | https://discord.com/api/v10/guilds/685237806360035354/members/468631903390400527
2022-09-18 14:28:32,606 DEBUG main.py | Starting request | POST | https://discord.com/api/v10/channels/1017545677674385529/messages
2022-09-18 14:28:32,613 DEBUG main.py | Starting request | POST | https://discord.com/api/v10/users/@me/channels
2022-09-18 14:28:32,658 ERROR client.py | Ignoring exception in on_command_error
Traceback (most recent call last):
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\main.py", line 127, in on_command_error
    message = await bot.owner.send(embed=template.error(f'```{tb_str}```', ctx.message.jump_url))
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\discord\abc.py", line 1497, in send
    channel = await self._get_channel()
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\discord\user.py", line 454, in _get_channel
    ch = await self.create_dm()
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\discord\user.py", line 496, in create_dm
    data: DMChannelPayload = await state.http.start_private_message(self.id)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\discord\http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\client.py", line 559, in _request
    await resp.start(conn)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\client_reqrep.py", line 583, in write_bytes
    await self.body.write(writer)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\payload.py", line 247, in write
    await writer.write(self._value)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\http_writer.py", line 89, in write
    await self._on_chunk_sent(chunk)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\client_reqrep.py", line 703, in _on_chunk_request_sent
    await trace.send_request_chunk_sent(method, url, chunk)
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiohttp\tracing.py", line 366, in send_request_chunk_sent
    return await self._trace_config.on_request_chunk_sent.send(
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\venv\lib\site-packages\aiosignal\__init__.py", line 36, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "C:\Users\Franky\Documents\ICT\Python\WF\wfg\bot\main.py", line 37, in on_request_chunk_sent
    json.dumps(json.loads(param.chunk, indent=4, ensure_ascii=False))
  File "C:\Users\Franky\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'indent'
2022-09-18 14:28:48,523 WARNING client.py | PyNaCl is not installed, voice will NOT be supported
2022-09-18 14:28:48,525 DEBUG client.py | setup_hook has successfully been registered as an event
2022-09-18 14:28:48,525 DEBUG proactor_events.py | Using proactor: IocpProactor
2022-09-18 14:28:48,527 INFO client.py | logging in using static token
2022-09-18 14:28:48,528 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/@me
2022-09-18 14:28:48,769 DEBUG main.py | Request ended | https://discord.com/api/v10/users/@me
2022-09-18 14:28:48,770 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/oauth2/applications/@me
2022-09-18 14:28:48,941 DEBUG main.py | Request ended | https://discord.com/api/v10/oauth2/applications/@me
2022-09-18 14:28:48,962 DEBUG main.py | Starting request | GET | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 14:28:49,331 DEBUG main.py | Request ended | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 14:28:49,587 INFO gateway.py | Shard ID None has connected to Gateway (Session ID: 7f2120e946292ccd0ec7da1fce5e8635).
2022-09-18 14:28:51,602 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/468631903390400527
2022-09-18 14:28:51,769 DEBUG main.py | Request ended | https://discord.com/api/v10/users/468631903390400527
2022-09-18 14:28:52,080 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/guilds/685237806360035354/members/468631903390400527
2022-09-18 14:28:52,245 DEBUG main.py | Request ended | https://discord.com/api/v10/guilds/685237806360035354/members/468631903390400527
2022-09-18 14:28:52,247 DEBUG main.py | Starting request | POST | https://discord.com/api/v10/channels/1017545677674385529/messages
2022-09-18 14:28:52,248 DEBUG main.py | request chunk sent | 
{
    "embeds": [
        {
            "footer": {
                "text": "1 winner | Hosted by: 07\ua78919#0719"
            },
            "fields": [
                {
                    "inline": true,
                    "name": "Hosted by:",
                    "value": "<@468631903390400527>"
                },
                {
                    "inline": true,
                    "name": "Ending:",
                    "value": "<t:1663507735:R> (<t:1663507735>)"
                }
            ],
            "color": 3066993,
            "type": "rich",
            "title": "1"
        }
    ],
    "content": null,
    "components": [],
    "tts": false
}
2022-09-18 14:28:52,475 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1017545677674385529/messages
2022-09-18 14:28:52,476 DEBUG main.py | Starting request | PUT | https://discord.com/api/v10/channels/1017545677674385529/messages/1021050180235169814/reactions/%F0%9F%8E%89/@me
2022-09-18 14:28:52,982 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1017545677674385529/messages/1021050180235169814/reactions/%F0%9F%8E%89/@me
2022-09-18 14:28:53,285 DEBUG main.py | Starting request | DELETE | https://discord.com/api/v10/channels/1017545677674385529/messages/1021050179023032471
2022-09-18 14:28:53,460 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1017545677674385529/messages/1021050179023032471
2022-09-18 14:28:55,015 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/channels/1017545677674385529/messages/1021050180235169814
2022-09-18 14:28:55,298 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1017545677674385529/messages/1021050180235169814
2022-09-18 14:28:55,299 DEBUG main.py | Starting request | PATCH | https://discord.com/api/v10/channels/1017545677674385529/messages/1021050180235169814
2022-09-18 14:28:55,299 DEBUG main.py | request chunk sent | 
{
    "embeds": [
        {
            "footer": {
                "text": "1 winner | Hosted by: 07\ua78919#0719"
            },
            "fields": [
                {
                    "name": "Hosted by:",
                    "value": "<@468631903390400527>",
                    "inline": true
                },
                {
                    "name": "Ended:",
                    "value": "<t:1663507735:R> (<t:1663507735>)",
                    "inline": true
                }
            ],
            "type": "rich",
            "title": "1"
        }
    ],
    "tts": false,
    "flags": 0
}
2022-09-18 14:28:55,508 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1017545677674385529/messages/1021050180235169814
2022-09-18 14:28:55,509 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/channels/1017545677674385529/messages/1021050180235169814/reactions/%F0%9F%8E%89?limit=1
2022-09-18 14:28:55,693 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1017545677674385529/messages/1021050180235169814/reactions/%F0%9F%8E%89?limit=1
2022-09-18 14:28:55,768 DEBUG main.py | Starting request | POST | https://discord.com/api/v10/channels/1017545677674385529/messages
2022-09-18 14:28:55,770 DEBUG main.py | request chunk sent | 
{
    "embeds": [
        {
            "type": "rich",
            "description": "\n[Jump to giveaway](https://discord.com/channels/685237806360035354/1017545677674385529/1021050180235169814)",
            "title": "No winner found!"
        }
    ],
    "content": null,
    "components": [],
    "tts": false
}
2022-09-18 14:28:55,960 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1017545677674385529/messages
2022-09-18 18:11:54,763 DEBUG main.py | Starting request | GET | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 18:11:54,949 DEBUG main.py | Request ended | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 18:11:55,069 INFO gateway.py | Shard ID None has successfully RESUMED session 7f2120e946292ccd0ec7da1fce5e8635.
2022-09-18 20:47:02,923 DEBUG main.py | Starting request | GET | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 20:47:03,137 DEBUG main.py | Request ended | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 20:47:03,268 INFO gateway.py | Shard ID None has successfully RESUMED session 7f2120e946292ccd0ec7da1fce5e8635.
2022-09-18 22:37:20,664 DEBUG main.py | Starting request | GET | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 22:37:20,853 DEBUG main.py | Request ended | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-18 22:37:20,966 INFO gateway.py | Shard ID None has successfully RESUMED session 7f2120e946292ccd0ec7da1fce5e8635.
2022-09-19 00:44:35,586 WARNING client.py | PyNaCl is not installed, voice will NOT be supported
2022-09-19 00:44:35,586 DEBUG client.py | setup_hook has successfully been registered as an event
2022-09-19 00:44:35,586 DEBUG proactor_events.py | Using proactor: IocpProactor
2022-09-19 00:44:35,587 INFO client.py | logging in using static token
2022-09-19 00:44:35,587 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/@me
2022-09-19 00:44:35,955 DEBUG main.py | Request ended | https://discord.com/api/v10/users/@me
2022-09-19 00:44:35,955 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/oauth2/applications/@me
2022-09-19 00:44:36,114 DEBUG main.py | Request ended | https://discord.com/api/v10/oauth2/applications/@me
2022-09-19 00:44:36,146 DEBUG main.py | Starting request | GET | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-19 00:44:36,512 DEBUG main.py | Request ended | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-19 00:44:36,722 INFO gateway.py | Shard ID None has connected to Gateway (Session ID: 1402f6bf9d687d9e7fedf357e941ecac).
2022-09-19 00:44:38,737 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/468631903390400527
2022-09-19 00:44:38,888 DEBUG main.py | Request ended | https://discord.com/api/v10/users/468631903390400527
2022-09-19 00:46:14,421 WARNING client.py | PyNaCl is not installed, voice will NOT be supported
2022-09-19 00:46:14,423 DEBUG client.py | setup_hook has successfully been registered as an event
2022-09-19 00:46:14,423 DEBUG proactor_events.py | Using proactor: IocpProactor
2022-09-19 00:46:14,425 INFO client.py | logging in using static token
2022-09-19 00:46:14,426 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/@me
2022-09-19 00:46:14,736 DEBUG main.py | Request ended | https://discord.com/api/v10/users/@me
2022-09-19 00:46:14,737 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/oauth2/applications/@me
2022-09-19 00:46:14,894 DEBUG main.py | Request ended | https://discord.com/api/v10/oauth2/applications/@me
2022-09-19 00:46:14,912 DEBUG main.py | Starting request | GET | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-19 00:46:15,250 DEBUG main.py | Request ended | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-19 00:46:15,443 INFO gateway.py | Shard ID None has connected to Gateway (Session ID: 12a5566de889d9d876ae7a3ca1461fb3).
2022-09-19 00:46:17,466 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/468631903390400527
2022-09-19 00:46:17,630 DEBUG main.py | Request ended | https://discord.com/api/v10/users/468631903390400527
2022-09-19 01:36:37,292 DEBUG main.py | Starting request | GET | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-19 01:36:37,468 DEBUG main.py | Request ended | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-19 01:36:37,583 INFO gateway.py | Shard ID None has successfully RESUMED session 12a5566de889d9d876ae7a3ca1461fb3.
2022-09-19 18:25:18,074 WARNING client.py | PyNaCl is not installed, voice will NOT be supported
2022-09-19 18:25:18,075 DEBUG client.py | setup_hook has successfully been registered as an event
2022-09-19 18:25:18,076 DEBUG proactor_events.py | Using proactor: IocpProactor
2022-09-19 18:25:18,077 INFO client.py | logging in using static token
2022-09-19 18:25:18,077 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/@me
2022-09-19 18:25:18,419 DEBUG main.py | Request ended | https://discord.com/api/v10/users/@me
2022-09-19 18:25:18,419 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/oauth2/applications/@me
2022-09-19 18:25:18,601 DEBUG main.py | Request ended | https://discord.com/api/v10/oauth2/applications/@me
2022-09-19 18:25:18,624 DEBUG main.py | Starting request | GET | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-19 18:25:18,991 DEBUG main.py | Request ended | wss://gateway.discord.gg/?v=10&encoding=json&compress=zlib-stream
2022-09-19 18:25:19,229 INFO gateway.py | Shard ID None has connected to Gateway (Session ID: 33e45f9b516a6b5a2fc03b0d62ec7e51).
2022-09-19 18:25:21,249 DEBUG main.py | Starting request | GET | https://discord.com/api/v10/users/468631903390400527
2022-09-19 18:25:21,413 DEBUG main.py | Request ended | https://discord.com/api/v10/users/468631903390400527
2022-09-19 18:25:50,906 DEBUG main.py | Starting request | POST | https://discord.com/api/v10/users/@me/channels
2022-09-19 18:25:50,953 DEBUG main.py | request chunk sent | b'{"recipient_id":468631903390400527}'
2022-09-19 18:25:51,125 DEBUG main.py | Request ended | https://discord.com/api/v10/users/@me/channels
2022-09-19 18:25:51,126 DEBUG main.py | Starting request | POST | https://discord.com/api/v10/channels/1016708510374957076/messages
2022-09-19 18:25:51,127 DEBUG main.py | request chunk sent | b'{"embeds":[{"color":15158332,"type":"rich","description":"```Traceback (most recent call last):\\n  File \\"C:\\\\Users\\\\Franky\\\\Documents\\\\ICT\\\\Python\\\\WF\\\\wfg\\\\bot\\\\venv\\\\lib\\\\site-packages\\\\discord\\\\ext\\\\commands\\\\core.py\\", line 229, in wrapped\\n    ret = await coro(*args, **kwargs)\\n  File \\"C:\\\\Users\\\\Franky\\\\Documents\\\\ICT\\\\Python\\\\WF\\\\wfg\\\\bot\\\\cogs\\\\giveaways.py\\", line 167, in start\\n    duration, winners, description, kwargs = args\\nValueError: not enough values to unpack (expected 4, got 1)\\n\\nThe above exception was the direct cause of the following exception:\\n\\nTraceback (most recent call last):\\n  File \\"C:\\\\Users\\\\Franky\\\\Documents\\\\ICT\\\\Python\\\\WF\\\\wfg\\\\bot\\\\venv\\\\lib\\\\site-packages\\\\discord\\\\ext\\\\commands\\\\bot.py\\", line 1347, in invoke\\n    await ctx.command.invoke(ctx)\\n  File \\"C:\\\\Users\\\\Franky\\\\Documents\\\\ICT\\\\Python\\\\WF\\\\wfg\\\\bot\\\\venv\\\\lib\\\\site-packages\\\\discord\\\\ext\\\\commands\\\\core.py\\", line 1023, in invoke\\n    await injected(*ctx.args, **ctx.kwargs)  # type: ignore\\n  File \\"C:\\\\Users\\\\Franky\\\\Documents\\\\ICT\\\\Python\\\\WF\\\\wfg\\\\bot\\\\venv\\\\lib\\\\site-packages\\\\discord\\\\ext\\\\commands\\\\core.py\\", line 238, in wrapped\\n    raise CommandInvokeError(exc) from exc\\n\\ndiscord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: not enough values to unpack (expected 4, got 1)\\n```\\n[Jump](https://discord.com/channels/685237806360035354/687065667450437642/1021472200773087312)","title":"Error"}],"content":null,"components":[],"tts":false}'
2022-09-19 18:25:51,523 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/1016708510374957076/messages
2022-09-19 18:25:51,524 DEBUG main.py | Starting request | POST | https://discord.com/api/v10/channels/687065667450437642/messages
2022-09-19 18:25:51,525 DEBUG main.py | request chunk sent | b'{"embeds":[{"color":15158332,"type":"rich","description":"Internal Error, report submitted.\\n[Jump](https://discord.com/channels/@me/1016708510374957076/1021472203381940324)","title":"Error"}],"content":null,"components":[],"tts":false}'
2022-09-19 18:25:51,841 DEBUG main.py | Request ended | https://discord.com/api/v10/channels/687065667450437642/messages
